// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oefzgirftcdkgpnwvhfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lZnpnaXJmdGNka2dwbnd2aGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjU1OTEsImV4cCI6MjA2NzA0MTU5MX0.UfqjnkMFvmv4Plu8g2Yzl2vUtw5-GHAdBYTAgDTb4wg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});